name: Vavoo M3U Generator

on:
  schedule:
    - cron: '0 */4 * * *' # Her 4 saatte bir çalışır (İstersen değiştirebilirsin)
  workflow_dispatch: # Manuel tetikleme butonu ekler

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Chrome Tarayıcı Kurulumu
      uses: browser-actions/setup-chrome@latest

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt

    - name: Scripti Çalıştır (main.py)
      run: python main.py

    - name: Dosyayı Commit ve Push Yap
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add vavoo_playlist.m3u
        git commit -m "Playlist Guncellendi: $(date)" || echo "Değişiklik yok"
        git push
