name: TRGoals M3U Güncelleyici

on:
  schedule:
    - cron: '*/30 * * * *' # 30 dakikada bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Chrome Kurulumu (Garanti olsun diye)
        uses: browser-actions/setup-chrome@latest

      - name: Botu Çalıştır
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1" # Çıktıları anlık görmek için
        run: python -u main.py
